# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nlight/dev/sphereflake-raytracer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nlight/dev/sphereflake-raytracer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nlight/dev/sphereflake-raytracer/CMakeFiles /home/nlight/dev/sphereflake-raytracer/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nlight/dev/sphereflake-raytracer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sphereflake-sse3

# Build rule for target.
sphereflake-sse3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sphereflake-sse3
.PHONY : sphereflake-sse3

# fast build rule for target.
sphereflake-sse3/fast:
	$(MAKE) -f CMakeFiles/sphereflake-sse3.dir/build.make CMakeFiles/sphereflake-sse3.dir/build
.PHONY : sphereflake-sse3/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f lib/glfw/CMakeFiles/uninstall.dir/build.make lib/glfw/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) -f lib/glfw/src/CMakeFiles/glfw.dir/build.make lib/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

sphereflake/GLFramebufferObject.o: sphereflake/GLFramebufferObject.cpp.o
.PHONY : sphereflake/GLFramebufferObject.o

# target to build an object file
sphereflake/GLFramebufferObject.cpp.o:
	$(MAKE) -f CMakeFiles/sphereflake-sse3.dir/build.make CMakeFiles/sphereflake-sse3.dir/sphereflake/GLFramebufferObject.cpp.o
.PHONY : sphereflake/GLFramebufferObject.cpp.o

sphereflake/GLFramebufferObject.i: sphereflake/GLFramebufferObject.cpp.i
.PHONY : sphereflake/GLFramebufferObject.i

# target to preprocess a source file
sphereflake/GLFramebufferObject.cpp.i:
	$(MAKE) -f CMakeFiles/sphereflake-sse3.dir/build.make CMakeFiles/sphereflake-sse3.dir/sphereflake/GLFramebufferObject.cpp.i
.PHONY : sphereflake/GLFramebufferObject.cpp.i

sphereflake/GLFramebufferObject.s: sphereflake/GLFramebufferObject.cpp.s
.PHONY : sphereflake/GLFramebufferObject.s

# target to generate assembly for a file
sphereflake/GLFramebufferObject.cpp.s:
	$(MAKE) -f CMakeFiles/sphereflake-sse3.dir/build.make CMakeFiles/sphereflake-sse3.dir/sphereflake/GLFramebufferObject.cpp.s
.PHONY : sphereflake/GLFramebufferObject.cpp.s

sphereflake/GLProgram.o: sphereflake/GLProgram.cpp.o
.PHONY : sphereflake/GLProgram.o

# target to build an object file
sphereflake/GLProgram.cpp.o:
	$(MAKE) -f CMakeFiles/sphereflake-sse3.dir/build.make CMakeFiles/sphereflake-sse3.dir/sphereflake/GLProgram.cpp.o
.PHONY : sphereflake/GLProgram.cpp.o

sphereflake/GLProgram.i: sphereflake/GLProgram.cpp.i
.PHONY : sphereflake/GLProgram.i

# target to preprocess a source file
sphereflake/GLProgram.cpp.i:
	$(MAKE) -f CMakeFiles/sphereflake-sse3.dir/build.make CMakeFiles/sphereflake-sse3.dir/sphereflake/GLProgram.cpp.i
.PHONY : sphereflake/GLProgram.cpp.i

sphereflake/GLProgram.s: sphereflake/GLProgram.cpp.s
.PHONY : sphereflake/GLProgram.s

# target to generate assembly for a file
sphereflake/GLProgram.cpp.s:
	$(MAKE) -f CMakeFiles/sphereflake-sse3.dir/build.make CMakeFiles/sphereflake-sse3.dir/sphereflake/GLProgram.cpp.s
.PHONY : sphereflake/GLProgram.cpp.s

sphereflake/SSAO.o: sphereflake/SSAO.cpp.o
.PHONY : sphereflake/SSAO.o

# target to build an object file
sphereflake/SSAO.cpp.o:
	$(MAKE) -f CMakeFiles/sphereflake-sse3.dir/build.make CMakeFiles/sphereflake-sse3.dir/sphereflake/SSAO.cpp.o
.PHONY : sphereflake/SSAO.cpp.o

sphereflake/SSAO.i: sphereflake/SSAO.cpp.i
.PHONY : sphereflake/SSAO.i

# target to preprocess a source file
sphereflake/SSAO.cpp.i:
	$(MAKE) -f CMakeFiles/sphereflake-sse3.dir/build.make CMakeFiles/sphereflake-sse3.dir/sphereflake/SSAO.cpp.i
.PHONY : sphereflake/SSAO.cpp.i

sphereflake/SSAO.s: sphereflake/SSAO.cpp.s
.PHONY : sphereflake/SSAO.s

# target to generate assembly for a file
sphereflake/SSAO.cpp.s:
	$(MAKE) -f CMakeFiles/sphereflake-sse3.dir/build.make CMakeFiles/sphereflake-sse3.dir/sphereflake/SSAO.cpp.s
.PHONY : sphereflake/SSAO.cpp.s

sphereflake/Sobol.o: sphereflake/Sobol.cpp.o
.PHONY : sphereflake/Sobol.o

# target to build an object file
sphereflake/Sobol.cpp.o:
	$(MAKE) -f CMakeFiles/sphereflake-sse3.dir/build.make CMakeFiles/sphereflake-sse3.dir/sphereflake/Sobol.cpp.o
.PHONY : sphereflake/Sobol.cpp.o

sphereflake/Sobol.i: sphereflake/Sobol.cpp.i
.PHONY : sphereflake/Sobol.i

# target to preprocess a source file
sphereflake/Sobol.cpp.i:
	$(MAKE) -f CMakeFiles/sphereflake-sse3.dir/build.make CMakeFiles/sphereflake-sse3.dir/sphereflake/Sobol.cpp.i
.PHONY : sphereflake/Sobol.cpp.i

sphereflake/Sobol.s: sphereflake/Sobol.cpp.s
.PHONY : sphereflake/Sobol.s

# target to generate assembly for a file
sphereflake/Sobol.cpp.s:
	$(MAKE) -f CMakeFiles/sphereflake-sse3.dir/build.make CMakeFiles/sphereflake-sse3.dir/sphereflake/Sobol.cpp.s
.PHONY : sphereflake/Sobol.cpp.s

sphereflake/Sphereflake.o: sphereflake/Sphereflake.cpp.o
.PHONY : sphereflake/Sphereflake.o

# target to build an object file
sphereflake/Sphereflake.cpp.o:
	$(MAKE) -f CMakeFiles/sphereflake-sse3.dir/build.make CMakeFiles/sphereflake-sse3.dir/sphereflake/Sphereflake.cpp.o
.PHONY : sphereflake/Sphereflake.cpp.o

sphereflake/Sphereflake.i: sphereflake/Sphereflake.cpp.i
.PHONY : sphereflake/Sphereflake.i

# target to preprocess a source file
sphereflake/Sphereflake.cpp.i:
	$(MAKE) -f CMakeFiles/sphereflake-sse3.dir/build.make CMakeFiles/sphereflake-sse3.dir/sphereflake/Sphereflake.cpp.i
.PHONY : sphereflake/Sphereflake.cpp.i

sphereflake/Sphereflake.s: sphereflake/Sphereflake.cpp.s
.PHONY : sphereflake/Sphereflake.s

# target to generate assembly for a file
sphereflake/Sphereflake.cpp.s:
	$(MAKE) -f CMakeFiles/sphereflake-sse3.dir/build.make CMakeFiles/sphereflake-sse3.dir/sphereflake/Sphereflake.cpp.s
.PHONY : sphereflake/Sphereflake.cpp.s

sphereflake/main.o: sphereflake/main.cpp.o
.PHONY : sphereflake/main.o

# target to build an object file
sphereflake/main.cpp.o:
	$(MAKE) -f CMakeFiles/sphereflake-sse3.dir/build.make CMakeFiles/sphereflake-sse3.dir/sphereflake/main.cpp.o
.PHONY : sphereflake/main.cpp.o

sphereflake/main.i: sphereflake/main.cpp.i
.PHONY : sphereflake/main.i

# target to preprocess a source file
sphereflake/main.cpp.i:
	$(MAKE) -f CMakeFiles/sphereflake-sse3.dir/build.make CMakeFiles/sphereflake-sse3.dir/sphereflake/main.cpp.i
.PHONY : sphereflake/main.cpp.i

sphereflake/main.s: sphereflake/main.cpp.s
.PHONY : sphereflake/main.s

# target to generate assembly for a file
sphereflake/main.cpp.s:
	$(MAKE) -f CMakeFiles/sphereflake-sse3.dir/build.make CMakeFiles/sphereflake-sse3.dir/sphereflake/main.cpp.s
.PHONY : sphereflake/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... install"
	@echo "... sphereflake-sse3"
	@echo "... list_install_components"
	@echo "... install/local"
	@echo "... uninstall"
	@echo "... glfw"
	@echo "... sphereflake/GLFramebufferObject.o"
	@echo "... sphereflake/GLFramebufferObject.i"
	@echo "... sphereflake/GLFramebufferObject.s"
	@echo "... sphereflake/GLProgram.o"
	@echo "... sphereflake/GLProgram.i"
	@echo "... sphereflake/GLProgram.s"
	@echo "... sphereflake/SSAO.o"
	@echo "... sphereflake/SSAO.i"
	@echo "... sphereflake/SSAO.s"
	@echo "... sphereflake/Sobol.o"
	@echo "... sphereflake/Sobol.i"
	@echo "... sphereflake/Sobol.s"
	@echo "... sphereflake/Sphereflake.o"
	@echo "... sphereflake/Sphereflake.i"
	@echo "... sphereflake/Sphereflake.s"
	@echo "... sphereflake/main.o"
	@echo "... sphereflake/main.i"
	@echo "... sphereflake/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

